Repository dwyl/content, pull requests merged in 2020-05, with the labels that each got.

#2 Remove IO.inspect
  lib/content.ex
  mix.exs
  test/content_test.exs
Labels: awaiting-review

#4 check if url terminates with .json
  lib/content.ex
  mix.exs
  test/content_test.exs
Labels: in-review

#5 Strip ".json" (or ".JSON") from conn.request_path
  README.md
  lib/content.ex
  mix.exs
  test/content_test.exs
Labels: awaiting-review

#6 Create wildcard_redirect/3 to redirect /*.json requests #3
  README.md
  config/config.exs
  lib/content.ex
  mix.exs
  mix.lock
  test/phoenix_wildcard_redirect_test.exs
Labels: awaiting-review, enhancement
